spring:
  data:
    mongodb:
      uri: mongodb://root:root@121.36.39.114:27018/mylib?authSource=admin&authMechanism=SCRAM-SHA-1
  application:
    name: mylib
server:
  port: 8080

mylib:
  security:
# 默认登陆成功页面
#    browser:
#      loginPage: /demo-signIn.html
# 登陆成功返回方式 ，转向或JSON形式返回
    browser:
        LoginType: REDIRECT



